<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What industry is your business in_app_5cbab0</name>
   <tag></tag>
   <elementGuidId>e8d5f71a-f6a5-43cc-a296-35f8c13a2605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appbundle_project_businessIndustry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#appbundle_project_businessIndustry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48e83fec-e45e-4475-8745-8c9fb27d21c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d6f36d2-9eca-46b7-b8d3-369c0cc81ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appbundle_project_businessIndustry</value>
      <webElementGuid>cd118e04-9931-4e94-a6c2-593ec3b310cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appbundle_project[businessIndustry]</value>
      <webElementGuid>93e8515f-f6f3-4e19-bbbb-18ffe6a0c598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your industry here</value>
      <webElementGuid>92215c17-8069-41be-af3f-5cab313ce37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d82aa6e3-cd61-464b-a563-565817d11969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>e713ca72-a745-44c1-9660-7ab8155619e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c475465a-208e-41c5-b55a-30ffc49976b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appbundle_project_businessIndustry&quot;)</value>
      <webElementGuid>571e8c0e-6e23-432c-932c-46a2e65da76e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appbundle_project_businessIndustry']</value>
      <webElementGuid>d9527a75-c298-4efb-a1b0-fa0179d0b167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-information']/div/div/div/input</value>
      <webElementGuid>b237f907-3c86-4631-99c7-fd6b61836fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>5b573ae0-e1f5-4687-81b1-228c485bc20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'appbundle_project_businessIndustry' and @name = 'appbundle_project[businessIndustry]' and @placeholder = 'Type your industry here']</value>
      <webElementGuid>f1e66449-3fd7-4007-a15b-c004e9a4c5de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
