<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where is your business headquartered__41750a</name>
   <tag></tag>
   <elementGuidId>3e34460f-69da-4c0a-918f-78c74147d8aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appbundle_project_businessHeadquarter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#appbundle_project_businessHeadquarter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ff01adf-9560-427f-a115-a556679fcd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9aa62cd-40c1-4e4f-81aa-a0ecf1f7cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appbundle_project_businessHeadquarter</value>
      <webElementGuid>89208565-7e41-42c6-b6c0-bb82fd62fe05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appbundle_project[businessHeadquarter]</value>
      <webElementGuid>8617b96b-0f7c-4678-ac08-c28c31af6bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your HQ address here</value>
      <webElementGuid>73868252-94d8-429b-bebf-dccf92fd38d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1a94fe40-6880-43a6-9b0c-62cc01dcfeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>745d645a-efd8-45d7-84a7-96e8643958f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e740624b-b661-42c6-9c77-599efba429b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appbundle_project_businessHeadquarter&quot;)</value>
      <webElementGuid>c86fb88d-58f2-4be4-a108-1ef79502b0cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appbundle_project_businessHeadquarter']</value>
      <webElementGuid>c975e994-f24b-42a4-aa76-27d84e03b754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-information']/div/div[4]/div/input</value>
      <webElementGuid>df19931e-797e-440e-b668-0c7448e2f96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>531a92fe-d18a-4d2f-932b-3fdcc753655c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'appbundle_project_businessHeadquarter' and @name = 'appbundle_project[businessHeadquarter]' and @placeholder = 'Type your HQ address here']</value>
      <webElementGuid>6853dba3-7115-4420-ac0c-94e64a90c458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
