<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Which products andor services do you _c71c75</name>
   <tag></tag>
   <elementGuidId>89744cde-9ea8-454b-b23a-3749940e8d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appbundle_project_servicesOffer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#appbundle_project_servicesOffer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c599492-c95b-47b4-90a1-8afb80d6cff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df6e2cd8-005f-402e-b07e-db5780fcf881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appbundle_project_servicesOffer</value>
      <webElementGuid>8b482b95-31ca-414b-b653-9987cecf832e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appbundle_project[servicesOffer]</value>
      <webElementGuid>600c47cc-c1b0-4c3d-9cc7-7030aac7afcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your products and/or services here</value>
      <webElementGuid>c70a421d-77aa-42a5-bea0-bccde4b0a2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de808129-0880-412d-b4a6-8d08415e4c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>eb844391-6b1f-4848-9a6d-67a1e1095ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d7ef7aca-2170-443e-8631-7d99178c8507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appbundle_project_servicesOffer&quot;)</value>
      <webElementGuid>259e44c4-caac-4b0f-aad4-327c7b508434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appbundle_project_servicesOffer']</value>
      <webElementGuid>7c47ef3b-2960-4af1-b249-16cfa6583a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-information']/div/div[3]/div/input</value>
      <webElementGuid>79f61415-afc7-4401-ba77-bacbc55a38dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/input</value>
      <webElementGuid>918e5782-471f-41b9-b395-7f9cd7650f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'appbundle_project_servicesOffer' and @name = 'appbundle_project[servicesOffer]' and @placeholder = 'Type your products and/or services here']</value>
      <webElementGuid>32bdd2cc-9c53-441c-a315-3e2e84eea961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
