<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_100</name>
   <tag></tag>
   <elementGuidId>2bc632a0-7957-4e3f-8a31-acda4ecaa28c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div/div[2]/div/div/div/a/div/h3/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.m-b-10.purple-clr > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e2a185bf-2c9a-439d-8afd-b47088723fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                          100%
                                                                          </value>
      <webElementGuid>cd33cd58-e1c5-4dc0-9daa-012305474ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row dash-four-card&quot;]/div[@class=&quot;col-lg-3 col-md-6 col-sm-6 print-col-6&quot;]/a[1]/div[@class=&quot;card-box widget-box-three&quot;]/h3[@class=&quot;m-b-10 purple-clr&quot;]/span[1]</value>
      <webElementGuid>6c91f69a-7bc7-4ff2-98a9-bc5cfc79aa9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div[2]/div/div/div/a/div/h3/span</value>
      <webElementGuid>f58f7443-d14d-4d63-b8bb-eef0111b3857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[1]</value>
      <webElementGuid>15e95bee-5384-446c-aeba-983fe294a92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discussions'])[2]/preceding::span[2]</value>
      <webElementGuid>2ebf8cea-af9d-4667-b67b-0b30aa536589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::span[2]</value>
      <webElementGuid>4179460f-ddee-4150-91e3-f01d8d360903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100%']/parent::*</value>
      <webElementGuid>0809baec-9102-4a26-9475-526fe1350a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span</value>
      <webElementGuid>00f5acbb-3214-48a4-84b4-3016d23072f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                                                          100%
                                                                          ' or . = '
                                                                          100%
                                                                          ')]</value>
      <webElementGuid>250f3b0b-3973-425f-afbe-069928327d47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
