<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Singapore</name>
   <tag></tag>
   <elementGuidId>f825b58c-e8b5-4d31-a11b-c1db4bc7dfb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-appbundle_project_country-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-appbundle_project_country-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21ceea1a-f5ee-4fe3-83b5-588e04f9c569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>58c20825-be3d-454f-8d7b-a36db1f96aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-appbundle_project_country-container</value>
      <webElementGuid>2a1e7030-802d-4738-b7d3-b8de71d42dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Singapore</value>
      <webElementGuid>2e9e04fd-2aa6-45a1-bec1-13432b718c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singapore</value>
      <webElementGuid>c0ef52e4-c84a-47f5-8430-86bb6a58ae17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-appbundle_project_country-container&quot;)</value>
      <webElementGuid>947ba3bc-3fcb-46e2-be5e-be1c1e2a3348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-appbundle_project_country-container']</value>
      <webElementGuid>770e87cd-fa77-4c1b-9d7a-5c61a89f4170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-information']/div/div[2]/div[2]/span/span/span/span</value>
      <webElementGuid>43145ed0-0b93-4d55-a4c4-d7f20dfeb59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your key target country?'])[2]/following::span[4]</value>
      <webElementGuid>ef355e7a-c69f-485c-bbc6-027d2006de77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localizing SEO can yield much better results'])[1]/following::span[4]</value>
      <webElementGuid>aa6ac405-d631-42eb-b922-dbef98463a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Which products and/or services do you offer?'])[1]/preceding::span[3]</value>
      <webElementGuid>68c7a5f1-f279-455c-825f-13463bc2ff5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where is your business headquartered?'])[1]/preceding::span[3]</value>
      <webElementGuid>102a7d60-75cc-4c57-b326-148aa11495fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>ddbe8b1a-6d99-4b55-98ec-61c8ab5f59c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-appbundle_project_country-container' and @title = 'Singapore' and (text() = 'Singapore' or . = 'Singapore')]</value>
      <webElementGuid>ad6fcabf-592f-4bd7-861d-0f1818a89144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
