<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Testing</name>
   <tag></tag>
   <elementGuidId>d7da3452-6822-4ace-93b9-7deb80084b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='appbundle_project_aboutBusiness']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#appbundle_project_aboutBusiness</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>efd8b2fe-450c-4869-ad2f-fcbf8c849ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appbundle_project_aboutBusiness</value>
      <webElementGuid>cac89963-bda6-464c-af0e-63ac0b0f268f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appbundle_project[aboutBusiness]</value>
      <webElementGuid>893ea062-953a-4bf8-a2fc-38d572386394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your anwer here</value>
      <webElementGuid>845a4809-a657-45a9-a4df-f8eb24ce3dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e54ccb3f-3529-4df7-a690-716ae4c4ac37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>90d8fe10-3315-4fe3-996c-e628d22844f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appbundle_project_aboutBusiness&quot;)</value>
      <webElementGuid>ba2b3d43-9eba-470c-91d7-2f5182b58532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='appbundle_project_aboutBusiness']</value>
      <webElementGuid>1c633e9d-2fb6-46ba-902a-1e30b33eb2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-information']/div/div[6]/div/textarea</value>
      <webElementGuid>785fe4e8-cfbb-42a6-a2d4-2df19e643882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anything else about your business that you think we should know?'])[1]/following::textarea[1]</value>
      <webElementGuid>328031f0-2784-4a73-8840-4b3819363605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTC'])[2]/following::textarea[1]</value>
      <webElementGuid>106f0cd5-bc27-4387-86e3-a2c210cc2736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEO Information'])[2]/preceding::textarea[1]</value>
      <webElementGuid>730a194e-3c05-4b8b-be1b-f60f0319e166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List your top 3 industry competitor websites'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b3422fad-4a48-487b-96bd-5f99aabef49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing']/parent::*</value>
      <webElementGuid>c73aad51-d6ed-47af-a181-b85b03be6cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>812ce62c-a2d8-4928-94cd-21230b1f07b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'appbundle_project_aboutBusiness' and @name = 'appbundle_project[aboutBusiness]' and @placeholder = 'Type your anwer here' and (text() = 'Testing' or . = 'Testing')]</value>
      <webElementGuid>856301ef-3356-4723-a33d-ca2a1ca98f0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
