<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View All</name>
   <tag></tag>
   <elementGuidId>7611fe7e-a4f7-4c0f-89f4-2f4e76586848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div/div[3]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dash-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3d4edb1-98f5-4303-96f7-d57d62ccbc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/rcportal/user/conversation/list/3aa3f64913bd6cfaf699/active</value>
      <webElementGuid>6e37ae09-36af-476f-b34a-bff94278702d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dash-link</value>
      <webElementGuid>2ba29690-b4b5-4a20-abcc-83c37003a3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View All</value>
      <webElementGuid>1db67b6e-1838-4c59-9717-83353f2f589d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-box discussions dash-discuss&quot;]/a[@class=&quot;dash-link&quot;]</value>
      <webElementGuid>825439e6-a1f3-41b6-b87f-45e2d14f13c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div[3]/div/div/a</value>
      <webElementGuid>079bb7af-d70c-4abb-bca6-0b5189727f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View All')]</value>
      <webElementGuid>c1c30468-b48f-4b11-8b8b-c6dea4354eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discussions'])[2]/following::a[1]</value>
      <webElementGuid>491af4b1-afa3-4119-9c80-bd1667aedb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[3]</value>
      <webElementGuid>0786c279-70ef-4311-935a-1d9be21c198e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sem'])[1]/preceding::a[1]</value>
      <webElementGuid>1c4b8e60-9bf5-4620-8209-70c91a4280ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sem'])[2]/preceding::a[2]</value>
      <webElementGuid>f7cd7b03-f91c-4d6b-bd7f-a1feb0724c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View All']/parent::*</value>
      <webElementGuid>3af3d635-0a10-418e-b5c4-63b07a0cf1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/rcportal/user/conversation/list/3aa3f64913bd6cfaf699/active')])[2]</value>
      <webElementGuid>1e25ac26-bc6a-419a-bdee-df15fd7ed9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/a</value>
      <webElementGuid>53c6e892-7aad-4c70-a7cb-267a4b1f8e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/rcportal/user/conversation/list/3aa3f64913bd6cfaf699/active' and (text() = 'View All' or . = 'View All')]</value>
      <webElementGuid>6eb53609-6e59-4ff7-a965-a94b1f9f177c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
