<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>17c18745-7725-4f1f-ba3d-db7fd10301de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div/div[2]/div/div[2]/div/div/div[3]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown > a.dropdown-toggle.waves-effect > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef5d2753-e809-41e2-a68c-cda376406bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rankchutney.com/wp-content/plugins/wordpress-portal/web/assets/images/list-ico.png</value>
      <webElementGuid>d09f6546-1b9a-4a54-99b3-5a34a03d75de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;card-box discussions&quot;]/div[@class=&quot;inbox-widget m-t-20&quot;]/div[@class=&quot;inbox-item&quot;]/div[@class=&quot;three-dots text-right&quot;]/div[@class=&quot;dropdown&quot;]/a[@class=&quot;dropdown-toggle waves-effect&quot;]/img[1]</value>
      <webElementGuid>ccc969e4-0ee1-48ed-b923-2cef200fc0d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div[2]/div/div[2]/div/div/div[3]/div/a/img</value>
      <webElementGuid>c27787a5-1723-46bf-a2ba-201d294b2a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://rankchutney.com/wp-content/plugins/wordpress-portal/web/assets/images/list-ico.png')]</value>
      <webElementGuid>ded810c0-525d-4055-b799-4e3d0f634741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>4796dc8d-dd41-4774-be6d-855989ec2fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rankchutney.com/wp-content/plugins/wordpress-portal/web/assets/images/list-ico.png']</value>
      <webElementGuid>3285616c-ad1a-4f33-a75e-165964e6a335</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
