<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Access Provided</name>
   <tag></tag>
   <elementGuidId>5d408736-daee-4e96-8769-3ad1b458c21b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appbundle_project_googleAnalyticsAccess']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.form-check-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e0662bf7-864b-4114-8d65-a7c839062fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>e76e863b-635d-4c0d-a878-de4b3f764e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>appbundle_project_googleAnalyticsAccess_0</value>
      <webElementGuid>5dee65d6-b059-40b3-900d-8ca2cc394392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Access Provided</value>
      <webElementGuid>e907d79d-f73d-4e7b-ace1-efe19d984d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appbundle_project_googleAnalyticsAccess&quot;)/div[@class=&quot;form-check&quot;]/label[@class=&quot;form-check-label&quot;]</value>
      <webElementGuid>8e7148b8-4cc6-4a2e-9131-15cf7a215ffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appbundle_project_googleAnalyticsAccess']/div/label</value>
      <webElementGuid>38d0d0ce-42fb-4532-bc15-195325d94a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking'])[2]/following::label[1]</value>
      <webElementGuid>70f42b6f-8570-4d4e-aeff-48e8d4111456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Anything else you', &quot;'&quot;, 'd like to share?')])[1]/following::label[1]</value>
      <webElementGuid>45d012c4-8deb-4da0-aa40-275c88a34fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do not own/have access'])[1]/preceding::label[1]</value>
      <webElementGuid>3b61f222-931b-45fa-95c2-0fb3d74c59e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Provided'])[2]/preceding::label[2]</value>
      <webElementGuid>800a7e55-3142-419e-8b47-7e8afaefc1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Access Provided']/parent::*</value>
      <webElementGuid>aebf3462-545d-485b-a8a4-6892593b937d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/label</value>
      <webElementGuid>495d7220-92a4-4351-8d3e-518a626db375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Access Provided' or . = 'Access Provided')]</value>
      <webElementGuid>453cd34c-3046-4f3a-80b0-cab2c76f9568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
