<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What are the top keywords you,_f433d3</name>
   <tag></tag>
   <elementGuidId>a3b6cd40-c1f5-4502-bc82-922ecb12b57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appbundle_project_optimizeKeywords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#appbundle_project_optimizeKeywords</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6716a203-db46-4eb7-919d-8003fe5c0241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>972807ad-cbd5-40df-97ea-e5f372324507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appbundle_project_optimizeKeywords</value>
      <webElementGuid>2efdb288-914e-4b39-b96f-b163ab343b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appbundle_project[optimizeKeywords]</value>
      <webElementGuid>91bb921c-b87c-4b54-9466-91f7f6eaabe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your comma separated keywords here</value>
      <webElementGuid>fd384e8c-2aab-49d9-a8c9-265dd972d62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>13044e41-52b8-4071-aff5-7165b083f7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>test, test2, test3</value>
      <webElementGuid>18188d0a-73c5-4f93-8b8f-dd0f4a25811e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>46898607-473d-44da-899c-2af152d0e2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appbundle_project_optimizeKeywords&quot;)</value>
      <webElementGuid>aa7178c1-547a-46ac-b43b-884c934a085c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appbundle_project_optimizeKeywords']</value>
      <webElementGuid>2d248dd3-9da0-4b0e-a5a4-c541a0e196a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='seo-information']/div[2]/div/input</value>
      <webElementGuid>460fb5d9-4198-4c85-9ae6-9f3db49b6501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>b9df22e8-259e-4176-a6c1-1ba8418dced8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'appbundle_project_optimizeKeywords' and @name = 'appbundle_project[optimizeKeywords]' and @placeholder = 'Type your comma separated keywords here']</value>
      <webElementGuid>0fbe1353-2f3e-49ab-bd9d-3f44c3d5dbdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
