<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_List your top 3 industry competitor w_a54a55</name>
   <tag></tag>
   <elementGuidId>c7f7339a-dc74-4ce7-89a3-1c02b591dba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='topCompetitor[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;topCompetitor[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>968e7435-f7cb-4ea5-ab7b-ab06095209dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topCompetitor[]</value>
      <webElementGuid>ca8507d4-fb94-4eb1-81cb-f161f40d764e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>www.test.com</value>
      <webElementGuid>bec57fe9-8d7c-4934-a9ba-c3caa4355493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control m-b-10</value>
      <webElementGuid>f99a80c2-ffc8-42e3-8c2d-a0c71d8f2e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type website here</value>
      <webElementGuid>c184b286-e0f8-4c73-8614-d7ec7e46f7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f109498-eeaa-4b17-86e3-9d6b0eed3b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seo-information&quot;)/div[@class=&quot;col-sm-12 form-group&quot;]/input[@class=&quot;form-control m-b-10&quot;]</value>
      <webElementGuid>b7bf6292-4d9e-494d-8044-9bb19adfd0b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='topCompetitor[]']</value>
      <webElementGuid>de49ffba-d594-445b-bb91-43c600be36c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='seo-information']/div/input</value>
      <webElementGuid>e1b5ff35-9a41-4090-96b9-52c42ac9518f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>d6286bf0-cd7c-4d8b-b75f-aa05df4eaaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'topCompetitor[]' and @placeholder = 'Type website here']</value>
      <webElementGuid>73175101-6ace-4e70-9626-44055c4c1332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
