<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>98a5f954-7d4a-435c-a615-a406c739ddd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatable-buttons']/tbody/tr[2]/td[8]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5db8e95-9b43-4d49-811b-92e0636cfcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rankchutney.com/wp-content/plugins/wordpress-portal/web/assets/images/list-ico.png</value>
      <webElementGuid>1bd562b3-6f5f-459e-bdd0-0943d8526d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable-buttons&quot;)/tbody[@class=&quot;small&quot;]/tr[@class=&quot;even&quot;]/td[@class=&quot;actions&quot;]/div[@class=&quot;dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/img[1]</value>
      <webElementGuid>22ef4914-fe8a-4b53-a277-d600e2e52ca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable-buttons']/tbody/tr[2]/td[8]/div/a/img</value>
      <webElementGuid>e929fe6f-53df-41f3-b0f9-00180562e916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://rankchutney.com/wp-content/plugins/wordpress-portal/web/assets/images/list-ico.png')])[2]</value>
      <webElementGuid>bbcdfed4-95b3-4b36-8a01-277dbc7efc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/div/a/img</value>
      <webElementGuid>89ae90ed-0f88-4483-8a0a-06e2b53ac966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rankchutney.com/wp-content/plugins/wordpress-portal/web/assets/images/list-ico.png']</value>
      <webElementGuid>bb934322-415d-47b2-b32f-1b1bf70f601d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
